apiVersion: v1
kind: Secret
metadata:
  name: docker-images-secret-cronjobs
  namespace: cron-e2e-chart
data:
  .dockerconfigjson: {{ template "cron-e2e-chart.imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
